"""empty message

Revision ID: 92b5292a864d
Revises: ee4099d4c9a1
Create Date: 2018-10-24 19:04:06.820000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b5292a864d'
down_revision = 'ee4099d4c9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'title')
    # ### end Alembic commands ###
